baseURL = 'https://aottr.dev/'
languageCode = 'en-us'
title = 'aottr'
theme = 'aottr'
copyright = "AlexOttr"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10 # articles per page
summaryLength = 20

disableHugoGeneratorInject = true
enableGitInfo = false
enableRobotsTXT = true

removePathAccents = true
enableEmoji = true

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Thoughts on software development, data science, and other things."
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support
    customcss = ["css/main_overrides.css", "css/dark_overrides.css"]
  
  og_image = ""
  favicon = ""

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/aottr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alexottr/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:slug/'
  [permalinks.section]
    posts = '/posts/'
